### PR TITLE
Add: default handler for command

### PR DESCRIPTION
**Pull request by ahr1384**

### CODE REVIEW

**Comment by ahr1384** [comment]
@fabio-ivona how about it?

**Comment by fabio-ivona** [comment]
It could be better be handled as plain message

**Comment by ahr1384** [comment]
@fabio-ivona 
I want to know if it is a command type or a normal message

**Comment by fabio-ivona** [comment]
It can be detected from the leading slash

**Comment by ahr1384** [comment]
@fabio-ivona is it ok now؟

**Comment by fabio-ivona** [comment]
Will review it as soon as return from vacation (on 22nd of August)

**Comment by ahr1384** [comment]
it's true
Thank you

**Comment by fabio-ivona** [comment]
superseded by #148

**Pull request closed without merging**
