### PR TITLE
[feat] conditional methods

### PR DESCRIPTION
**Pull request by ahr1384**
add a method in Telegraph for if true run & if false don't run
like when function in Elquent Laravel

### CODE REVIEW

**Comment by ahr1384** [comment]
@fabio-ivona 
i test it & it is wrked in all method
& i trying to add to Keybord...

**Comment by ahr1384** [comment]
image

**Comment by ahr1384** [comment]
how it work in keyboards:
image
image

**Comment by fabio-ivona** [comment]
Thanks, this is a great improvement! 

I'll review this as soon as I come back from vacation (on 22nd of August)

Meanwhile, would you mind to add tests for this feature?

**Comment by ahr1384** [comment]
I am not very familiar with the tests section

**Comment by ahr1384** [comment]
please add Conditional methods docs in 
https://def-studio.github.io/telegraph/features/reply-keyboards
you just add in inline keyboard @fabio-ivona

**Comment by fabio-ivona** [comment]
done

**Pull request merged**
