### PR TITLE
feat: reply keyboards

### PR DESCRIPTION
**Pull request by fabio-ivona**
https://core.telegram.org/bots/api#replykeyboardmarkup

ref #89

Todo:
- [x] extend tests coverage
- [x] write docs

### CODE REVIEW

**Comment by fabio-ivona** [comment]
@intoeetive did you have any chance to test this feature?

**Comment by intoeetive** [comment]
sorry - not yet. Will do it today and will provide some feedback

**Comment by fabio-ivona** [comment]
No problem, this is open source. Time is not dued 😉

**Comment by intoeetive** [comment]
@fabio-ivona I have tested this with `requestLocation()` and `requestContact()`

Both requests are being sent correctly.

I can see the response from location request in my custom implementation of `handleChatMessage` (I think that's the best place to catch it?)

I don't see the data from contact request in `$this->message->toArray();` though - I think a function or two need to get added. I plan to work on that tonight and contribute (unless you have that ready :) )

**Comment by intoeetive** [comment]
Yes I'll contribute tonight. You should see a PR from me tomorrow morning (or a message in worst case)

It also looks like `reply_to_message_id` is not being processed - the location request shows in UI as a reply, but the received response (at least `->toArray()`) does not show that. Again, will try to look into it tonight.

Thank you!

**Comment by intoeetive** [comment]
Just found one thing - `removeReplyKeyboard()` does not seem to work. It does not generate any error, but it also does not remove the keyboard

**Comment by fabio-ivona** [comment]
Will check it tomorrow, thanks for pointing it out 😉

**Comment by fabio-ivona** [comment]
> Just found one thing - `removeReplyKeyboard()` does not seem to work. It does not generate any error, but it also does not remove the keyboard

@intoeetive could you past here the code you used to remove the keyboard?

**Comment by intoeetive** [comment]
I tried multiple approaches as I wasn't sure what's correct. None of them worked

`$this->chat->removeReplyKeyboard()`
`$this->chat->removeReplyKeyboard()->send()`
`$this->chat->markdown('...')->removeReplyKeyboard()`
`$this->chat->markdown('...')->removeReplyKeyboard()->send()`

I can give it another try, if you could tell me what's the right code to use :)

**Comment by fabio-ivona** [comment]
This code should work:

`$this->chat->markdown('...')->removeReplyKeyboard()->send()`

could you dump the result of ->send() call?

**Comment by fabio-ivona** [comment]
@intoeetive this is a test I just tried, it seems to work quite well:

```php
 Telegraph::message('you can use the calculator')->replyKeyboard(fn (ReplyKeyboard $k) => $k->buttons([
        ReplyButton::make(7)->width(0.25), ReplyButton::make(8)->width(0.25), ReplyButton::make(9)->width(0.25), ReplyButton::make('+')->width(0.25),
        ReplyButton::make(4)->width(0.25), ReplyButton::make(5)->width(0.25), ReplyButton::make(6)->width(0.25), ReplyButton::make('-')->width(0.25),
        ReplyButton::make(1)->width(0.25), ReplyButton::make(2)->width(0.25), ReplyButton::make(3)->width(0.25), ReplyButton::make('x')->width(0.25),
        ReplyButton::make(0)->width(0.25), ReplyButton::make('=')->width(0.75),
    ])->resize())->send();
    
 Telegraph::message('too late 😁')->removeReplyKeyboard()->send();
```

test


could you replicate this?

**Comment by intoeetive** [comment]
@fabio-ivona it worked this time for me too :)

Maybe I was trying to remove it with message which is not directly following it, not sure. Thank you - and sorry for false alert

**Comment by fabio-ivona** [comment]
> @fabio-ivona it worked this time for me too :)
> 
> Maybe I was trying to remove it with message which is not directly following it, not sure. Thank you - and sorry for false alert

Actually, it should work even when you don't immediately follow :thinking: 

could you dump here the result of a failing send call?

**Pull request merged**
