### PR TITLE
[feat] command parameters

### PR DESCRIPTION
**Pull request by fabio-ivona**
fix #141

### CODE REVIEW

**Comment by ahr1384** [comment]
but not support default handler for command #140 
@fabio-ivona

**Comment by ahr1384** [comment]
or add 
image
after('_')

**Comment by fabio-ivona** [comment]
Couldn't you add a space instead of _?

**Comment by ahr1384** [comment]
No
I send a list to user 
And I wand user click on command send it 
Bot with space can send it

**Comment by ahr1384** [comment]
default chat message is very good for this

**Pull request merged**
