### PR TITLE
Add BaseUrl To store file

### PR DESCRIPTION
**Pull request by ahr1384**

### CODE REVIEW

**Comment by fabio-ivona** [comment]
I think it should be better to allow to override the api url from a config setting, I'll take a look a it soon as it return from vacation (on 22nd of August)

**Comment by ahr1384** [comment]
@fabio-ivona 
Yes, I can do that too
But I did this because I don't want the value in the config to be used in some requests.
And we can change it every time
It is better if you do it yourself
Please put a method for it that can be changed in every request

**Comment by fabio-ivona** [comment]
I have something handy in mind, but it requires a bit of refactor, I can do it after 22nd of August

**Comment by fabio-ivona** [comment]
implemented, will be released today

**Pull request closed without merging**
