### PR TITLE
Web app inline keyboard

### PR DESCRIPTION
**Pull request by fabio-ivona**
This PR will add a new keyboard button type: Web App url

### CODE REVIEW

**Comment by ArthurPatriot** [comment]
Ahahaha, same as my pr)

**Comment by fabio-ivona** [comment]
Yep, saw you closed it, but it was a good add-on, so I implemented it

**Comment by ArthurPatriot** [comment]
I have a lot of improvements, but haven't time) Need add another keyboard. Now package support only `inline_keyboard`

**Comment by fabio-ivona** [comment]
I am working on the reply keyboard right now 😅 but still designing the api, want to build something that can use the same classes and api than inline keyboards, but still want to avoid confusion as their methods would be different

If you have any idea, let's share and work together!

**Pull request merged**
